export interface LegalDocument {
  title: string;
  updated: string;
  sections: [string, string][];
}

export const LEGAL_DOCS: Record<string, LegalDocument> = {
  terms: {
    title: 'Terms of Service',
    updated: 'September 1, 2026',
    sections: [
      [
        '1. Who we are',
        'DIGITALYCloud is operated by DIGITALY SAS (SIREN 933 877 508), headquartered at 254 Rue Vendôme, 69003 Lyon, France. These terms govern your use of the DIGITALYCloud website, dashboard and hosting services.',
      ],
      ['2. Your account', 'You must provide accurate information and keep your credentials secure. You are responsible for all activity under your account, including services deployed by team members you invite.'],
      [
        '3. Plans and billing',
        'Paid plans are billed monthly in advance, VAT included. Upgrades take effect immediately and are prorated. Downgrades take effect at the next billing date. Unpaid invoices may lead to suspension after 14 days.',
      ],
      ['4. Acceptable use', 'You may not use the service for illegal content, malware, spam, cryptocurrency mining or attacks on other systems. See the Acceptable Use Policy for details.'],
      ['5. Availability', 'We target 99.9% monthly availability. Planned maintenance is announced on the status page at least 48 hours in advance.'],
      ['6. Termination', 'You can delete your account at any time from Settings. We may suspend services that violate these terms after notice, or immediately in case of abuse.'],
      ['7. Liability', 'To the extent permitted by law, our liability is limited to the amount you paid in the 12 months before the claim.'],
      ['8. Governing law', 'These terms are governed by French law. Disputes are handled by the courts of Lyon.'],
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    updated: 'September 1, 2026',
    sections: [
      ['Data we collect', 'Account data (name, email), billing data processed by our payment provider, and technical data such as logs and metrics generated by your services.'],
      [
        'Where data is stored',
        'Customer data is stored in the region chosen for each service. Free plans are hosted exclusively in France (Lyon and Paris). Services deployed in European regions keep their data in the European Union; services you choose to deploy outside Europe store their data in that region, under our data processing agreement.',
      ],
      ['How we use it', 'To provide and secure the service, send transactional emails, and improve the platform. We never sell your data.'],
      ['Retention', 'Logs are retained for up to 30 days depending on your plan. Account data is deleted within 30 days of account deletion, except where the law requires us to keep invoices.'],
      ['Your rights', 'Under GDPR you can access, correct, export or delete your data. Contact privacy@digitaly.fr and we will reply within 30 days.'],
      ['Cookies', 'We only use essential cookies required for sign-in. No advertising or third-party tracking cookies.'],
    ],
  },
  'acceptable-use': {
    title: 'Acceptable Use Policy',
    updated: 'September 1, 2026',
    sections: [
      ['Prohibited content', 'Illegal content, content that infringes intellectual property, and content promoting violence or hatred.'],
      ['Prohibited activities', 'Malware, phishing, spam, network scanning, DDoS attacks, cryptocurrency mining and attempts to bypass platform limits.'],
      ['Discord bots', 'Bots must respect the Discord Terms of Service and Developer Policy. Self-bots and raid tools are not allowed.'],
      ['Game servers', 'Cracked or pirated server software is not permitted. Respect the EULA of the game you host.'],
      ['Reporting abuse', 'Report abuse to abuse@digitaly.fr. We review every report within 24 hours.'],
    ],
  },
};
